using EdgeStudio.ViewModels;
using FluentAssertions;
using Xunit;

namespace EdgeStudioTests
{
    /// <summary>
    /// Tests for inspector visibility state driven by navigation flags on EdgeStudioViewModel.
    /// These test the computed IsStandardInspectorVisible property and the observable
    /// IsQueryActive / IsLoggingActive / IsSubscriptionActive flags directly,
    /// avoiding the need for a live Ditto instance or Avalonia dispatcher in unit tests.
    /// </summary>
    public class EdgeStudioViewModelInspectorTests
    {
        // EdgeStudioViewModel exposes IsQueryActive, IsLoggingActive, IsSubscriptionActive
        // as public setters (generated by [ObservableProperty]), so we can drive them
        // directly without going through the full navigation pipeline.

        private static EdgeStudioViewModelStub CreateStub() => new();

        #region IsStandardInspectorVisible

        [Fact]
        public void IsStandardInspectorVisible_WhenNoSpecialNav_IsTrue()
        {
            var sut = CreateStub();

            sut.IsQueryActive = false;
            sut.IsLoggingActive = false;
            sut.IsSubscriptionActive = false;

            sut.IsStandardInspectorVisible.Should().BeTrue();
        }

        [Fact]
        public void IsStandardInspectorVisible_WhenQueryActive_IsFalse()
        {
            var sut = CreateStub();
            sut.IsQueryActive = true;

            sut.IsStandardInspectorVisible.Should().BeFalse();
        }

        [Fact]
        public void IsStandardInspectorVisible_WhenLoggingActive_IsFalse()
        {
            var sut = CreateStub();
            sut.IsLoggingActive = true;

            sut.IsStandardInspectorVisible.Should().BeFalse();
        }

        [Fact]
        public void IsStandardInspectorVisible_WhenSubscriptionActive_IsFalse()
        {
            var sut = CreateStub();
            sut.IsSubscriptionActive = true;

            sut.IsStandardInspectorVisible.Should().BeFalse();
        }

        #endregion

        #region IsQueryActive transitions

        [Fact]
        public void NavigateToQuery_SetsIsQueryActiveTrue()
        {
            var sut = CreateStub();

            // Simulate what UpdateCurrentViews(Query) does
            sut.IsQueryActive = false;
            sut.IsLoggingActive = false;
            sut.IsSubscriptionActive = false;
            sut.IsQueryActive = true;

            sut.IsQueryActive.Should().BeTrue();
        }

        [Fact]
        public void NavigateAway_FromQuery_ClearsIsQueryActive()
        {
            var sut = CreateStub();
            sut.IsQueryActive = true;

            // Simulate SetStandardNavLayout() called when navigating away
            sut.IsQueryActive = false;
            sut.IsLoggingActive = false;
            sut.IsSubscriptionActive = false;

            sut.IsQueryActive.Should().BeFalse();
            sut.IsStandardInspectorVisible.Should().BeTrue();
        }

        #endregion

        #region Property change notifications

        [Fact]
        public void IsQueryActive_Change_RaisesIsStandardInspectorVisibleChanged()
        {
            var sut = CreateStub();
            var raised = new List<string?>();
            sut.PropertyChanged += (_, e) => raised.Add(e.PropertyName);

            sut.IsQueryActive = true;

            raised.Should().Contain(nameof(EdgeStudioViewModelStub.IsStandardInspectorVisible));
        }

        [Fact]
        public void IsLoggingActive_Change_RaisesIsStandardInspectorVisibleChanged()
        {
            var sut = CreateStub();
            var raised = new List<string?>();
            sut.PropertyChanged += (_, e) => raised.Add(e.PropertyName);

            sut.IsLoggingActive = true;

            raised.Should().Contain(nameof(EdgeStudioViewModelStub.IsStandardInspectorVisible));
        }

        [Fact]
        public void IsSubscriptionActive_Change_RaisesIsStandardInspectorVisibleChanged()
        {
            var sut = CreateStub();
            var raised = new List<string?>();
            sut.PropertyChanged += (_, e) => raised.Add(e.PropertyName);

            sut.IsSubscriptionActive = true;

            raised.Should().Contain(nameof(EdgeStudioViewModelStub.IsStandardInspectorVisible));
        }

        #endregion
    }

    /// <summary>
    /// Minimal stub that replicates only the inspector-related observable properties
    /// from EdgeStudioViewModel, without requiring Ditto, Avalonia, or DI setup.
    /// </summary>
    public partial class EdgeStudioViewModelStub : CommunityToolkit.Mvvm.ComponentModel.ObservableObject
    {
        [CommunityToolkit.Mvvm.ComponentModel.ObservableProperty]
        private bool _isQueryActive;

        [CommunityToolkit.Mvvm.ComponentModel.ObservableProperty]
        private bool _isLoggingActive;

        [CommunityToolkit.Mvvm.ComponentModel.ObservableProperty]
        private bool _isSubscriptionActive;

        public bool IsStandardInspectorVisible => !IsLoggingActive && !IsSubscriptionActive && !IsQueryActive;

        partial void OnIsQueryActiveChanged(bool value) => OnPropertyChanged(nameof(IsStandardInspectorVisible));
        partial void OnIsLoggingActiveChanged(bool value) => OnPropertyChanged(nameof(IsStandardInspectorVisible));
        partial void OnIsSubscriptionActiveChanged(bool value) => OnPropertyChanged(nameof(IsStandardInspectorVisible));
    }
}
